// export default [collection, scenery, life, festival, mood];
// eslint-disable-next-line import/no-unresolved
import Res from '@res';

const {
  iceLandBlue,
  seaOfClouds,
  partly,
  dating,
  christmas,
  halloween,
  coolSummer,
  loveAndDream,
} = Res.scenes;

export default [
  [],
  [
    {
      sceneId: 3,
      code: 'icelandBlue',
      name: 'icelandBlue',
      img: iceLandBlue,
      imgW: iceLandBlue,
      base64: 'AcgFMjIAAABkANRkAAAAAGQAtF0AAAAAZAC4XAAAAABkAMdkAAAAAA==',
      value: {
        version: 1,
        id: 3,
        mode: 5,
        interval: 50,
        time: 50,
        settingA: 0,
        settingB: 0,
        settingC: 0,
        colors: [
          {
            value: 100,
            hue: 212,
            saturation: 100,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 180,
            saturation: 93,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 184,
            saturation: 92,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 199,
            saturation: 100,
            brightness: 0,
            temperature: 0,
          },
        ],
      },
    },
    {
      sceneId: 6,
      code: 'seaOfClouds',
      name: 'seaOfClouds',
      img: seaOfClouds,
      imgW: seaOfClouds,
      base64: 'Ac0FMh4AAABkADIxAAAAAGQAJVgAAAAAZADUWgAAAABkAQxXAAAAAA==',
      value: {
        version: 1,
        id: 6,
        mode: 5,
        interval: 50,
        time: 30,
        settingA: 0,
        settingB: 0,
        settingC: 0,
        colors: [
          {
            value: 100,
            hue: 50,
            saturation: 49,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 37,
            saturation: 88,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 212,
            saturation: 90,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 268,
            saturation: 87,
            brightness: 0,
            temperature: 0,
          },
        ],
      },
    },
  ],
  [
    {
      sceneId: 29,
      code: 'party',
      name: 'party',
      img: partly,
      imgW: partly,
      base64: 'AdkDMg8AAABkAOZgAAAAAGQAxFQAAAAAZAA8LwAAAABkADJeAAAAAGQAAVQAAAAA',
      value: {
        version: 1,
        id: 29,
        mode: 3,
        interval: 50,
        time: 15,
        settingA: 0,
        settingB: 0,
        settingC: 0,
        colors: [
          {
            value: 100,
            hue: 230,
            saturation: 96,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 196,
            saturation: 84,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 60,
            saturation: 47,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 50,
            saturation: 94,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 1,
            saturation: 84,
            brightness: 0,
            temperature: 0,
          },
        ],
      },
    },
    {
      sceneId: 33,
      code: 'dating',
      name: 'dating',
      img: dating,
      imgW: dating,
      base64: 'AQoKMlMAAABkAS9eAAAAAGQBPjoAAAAAZADYVAAAAABkABlRAAAAAA==',
      value: {
        version: 1,
        id: 33,
        mode: 10,
        interval: 50,
        time: 83,
        settingA: 0,
        settingB: 0,
        settingC: 0,
        colors: [
          {
            value: 100,
            hue: 303,
            saturation: 94,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 318,
            saturation: 58,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 216,
            saturation: 84,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 25,
            saturation: 81,
            brightness: 0,
            temperature: 0,
          },
        ],
      },
    },
  ],
  [
    {
      sceneId: 34,
      code: 'christmas',
      name: 'christmas',
      img: christmas,
      imgW: christmas,
      base64: 'AQMDMgkAAABkAABkAAAAAGQAPGQAAAAAZAC7VAAAAABkAOpXAAAAAGQBCGMAAAAA',
      value: {
        version: 1,
        id: 34,
        mode: 3,
        interval: 50,
        time: 9,
        settingA: 0,
        settingB: 0,
        settingC: 0,
        colors: [
          {
            value: 100,
            hue: 0,
            saturation: 100,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 60,
            saturation: 100,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 187,
            saturation: 84,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 234,
            saturation: 87,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 264,
            saturation: 99,
            brightness: 0,
            temperature: 0,
          },
        ],
      },
    },
    {
      sceneId: 36,
      code: 'halloween',
      name: 'halloween',
      img: halloween,
      imgW: halloween,
      base64: 'AQkJMjIAAABkAApfAAAAAGQBBmQAAAAAZADvXAAAAABkALAsAAAAAGQAfFQAAAAA',
      value: {
        version: 1,
        id: 36,
        mode: 9,
        interval: 50,
        time: 50,
        settingA: 0,
        settingB: 0,
        settingC: 0,
        colors: [
          {
            value: 100,
            hue: 10,
            saturation: 95,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 262,
            saturation: 100,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 239,
            saturation: 92,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 176,
            saturation: 44,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 124,
            saturation: 84,
            brightness: 0,
            temperature: 0,
          },
        ],
      },
    },
  ],
  [
    {
      sceneId: 44,
      code: 'coolSummer',
      name: 'coolSummer',
      img: coolSummer,
      imgW: coolSummer,
      base64: 'AQMDMhwAAABkAMpkAAAAAGQAkkIAAAAAZADMSwAAAABkALwtAAAAAA==',
      value: {
        version: 1,
        id: 44,
        mode: 3,
        interval: 50,
        time: 28,
        settingA: 0,
        settingB: 0,
        settingC: 0,
        colors: [
          {
            value: 100,
            hue: 202,
            saturation: 100,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 146,
            saturation: 66,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 204,
            saturation: 75,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 188,
            saturation: 45,
            brightness: 0,
            temperature: 0,
          },
        ],
      },
    },
    {
      sceneId: 45,
      code: 'loveAndDream',
      name: 'loveAndDream',
      img: loveAndDream,
      imgW: loveAndDream,
      base64: 'AQoKMlQAAABkAUNWAAAAAGQBGlgAAAAA',
      value: {
        version: 1,
        id: 45,
        mode: 10,
        interval: 50,
        time: 84,
        settingA: 0,
        settingB: 0,
        settingC: 0,
        colors: [
          {
            value: 100,
            hue: 323,
            saturation: 86,
            brightness: 0,
            temperature: 0,
          },
          {
            value: 100,
            hue: 282,
            saturation: 88,
            brightness: 0,
            temperature: 0,
          },
        ],
      },
    },
  ],
];
