export default {
  power: 'switch',
  pm25: 'pm25',
  mode: 'mode',
  anion: 'anion',
  uv: 'uv',
  wet: 'wet',
  light: 'light',
  childLock: 'child_lock',
  airQuality: 'air-quality',
  filter: 'filter',
  speed: 'fan_speed_enum',
  countdownLeft: 'countdown_left',
  tempIndoor: 'temp_indoor',
  humidity: 'humidity',
  tvoc: 'tvoc',
  eco2: 'eco2',
  filterDays: 'filter_days',
  totalRuntime: 'total_runtime',
  totalPm: 'total_pm',
  filterReset: 'filter_reset',
  countdownSet: 'countdown_set',
};
