import { Utils } from 'tuya-panel-kit';
import { GradientDir, UIDataPropType } from './interface';

const { convertX: cx } = Utils.RatioUtils;

export const gradientDirMap = {
  [GradientDir.right]: { x1: '0%', y1: '0%', x2: '100%', y2: '0%' },
  [GradientDir.left]: { x1: '100%', y1: '0%', x2: '0%', y2: '0%' },
  [GradientDir.up]: { x1: '0%', y1: '100%', x2: '0%', y2: '0%' },
  [GradientDir.down]: { x1: '0%', y1: '0%', x2: '0%', y2: '100%' },
};

export const UIDataRectangle: UIDataPropType[] = [
  {
    width: cx(52),
    height: cx(18),
    pos: [0, 0],
    gradientDir: GradientDir.right,
    imgKey: 'e1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(54), 0],
    gradientDir: GradientDir.right,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(108), 0],
    gradientDir: GradientDir.right,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(162), 0],
    gradientDir: GradientDir.right,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(216), 0],
    gradientDir: GradientDir.right,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(70),
    pos: [cx(270), 0],
    gradientDir: GradientDir.down,
    imgKey: 'u1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(216), cx(52)],
    gradientDir: GradientDir.left,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(162), cx(52)],
    gradientDir: GradientDir.left,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(108), cx(52)],
    gradientDir: GradientDir.left,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(54), cx(52)],
    gradientDir: GradientDir.left,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(70),
    pos: [cx(0), cx(52)],
    gradientDir: GradientDir.down,
    imgKey: 'u2',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(54), cx(104)],
    gradientDir: GradientDir.right,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(108), cx(104)],
    gradientDir: GradientDir.right,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(162), cx(104)],
    gradientDir: GradientDir.right,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(216), cx(104)],
    gradientDir: GradientDir.right,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(70),
    pos: [cx(270), cx(104)],
    gradientDir: GradientDir.down,
    imgKey: 'u1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(216), cx(156)],
    gradientDir: GradientDir.left,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(162), cx(156)],
    gradientDir: GradientDir.left,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(108), cx(156)],
    gradientDir: GradientDir.left,
    imgKey: 'l1',
  },
  {
    width: cx(52),
    height: cx(18),
    pos: [cx(54), cx(156)],
    gradientDir: GradientDir.left,
    imgKey: 'l1',
  },
];

export const UIDataPipe: UIDataPropType[] = [
  {
    width: cx(81),
    height: cx(27),
    pos: [0, cx(144)],
    gradientDir: GradientDir.right,
    imgKey: 'e1',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(45), cx(90)],
    gradientDir: GradientDir.up,
    imgKey: 'l1',
  },
  {
    width: cx(81),
    height: cx(36),
    pos: [cx(45), cx(54)],
    gradientDir: GradientDir.right,
    imgKey: 'u1',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(90), cx(90)],
    gradientDir: GradientDir.down,
    imgKey: 'l2',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(90), cx(144)],
    gradientDir: GradientDir.down,
    imgKey: 'l2',
  },
  {
    width: cx(81),
    height: cx(36),
    pos: [cx(90), cx(198)],
    gradientDir: GradientDir.right,
    imgKey: 'u3',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(135), cx(144)],
    gradientDir: GradientDir.up,
    imgKey: 'l2',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(135), cx(90)],
    gradientDir: GradientDir.up,
    imgKey: 'l2',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(135), cx(36)],
    gradientDir: GradientDir.up,
    imgKey: 'l2',
  },
  {
    width: cx(81),
    height: cx(36),
    pos: [cx(135), 0],
    gradientDir: GradientDir.right,
    imgKey: 'u2',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(180), cx(36)],
    gradientDir: GradientDir.down,
    imgKey: 'l2',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(180), cx(90)],
    gradientDir: GradientDir.down,
    imgKey: 'l2',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(180), cx(144)],
    gradientDir: GradientDir.down,
    imgKey: 'l2',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(180), cx(198)],
    gradientDir: GradientDir.down,
    imgKey: 'l2',
  },
  {
    width: cx(81),
    height: cx(36),
    pos: [cx(180), cx(252)],
    gradientDir: GradientDir.right,
    imgKey: 'u3',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(225), cx(198)],
    gradientDir: GradientDir.up,
    imgKey: 'l2',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(225), cx(144)],
    gradientDir: GradientDir.up,
    imgKey: 'l2',
  },
  {
    width: cx(81),
    height: cx(36),
    pos: [cx(225), cx(108)],
    gradientDir: GradientDir.right,
    imgKey: 'u2',
  },
  {
    width: cx(36),
    height: cx(54),
    pos: [cx(270), cx(144)],
    gradientDir: GradientDir.down,
    imgKey: 'l3',
  },
  {
    width: cx(81),
    height: cx(27),
    pos: [cx(270), cx(198)],
    gradientDir: GradientDir.right,
    imgKey: 'e2',
  },
];

export const UIDataPoint: UIDataPropType[] = UIDataPipe;
