name: demorelease

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  demorelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: cd examples && COPYFILE_DISABLE=1 ls | xargs -I {} tar zcvfm {}.tar.gz {}
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./examples/*.tar.gz
          body: ${{steps.github_release.outputs.changelog}}
          draft: true
