name: demorelease

on: push

jobs:
  demorelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: COPYFILE_DISABLE=1 ls examples | xargs -I {} tar zcvfm {}.tar.gz examples/{}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./*.tar.gz
          draft: true